# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fb309a03831f6491d776852eb1002e4d1b363521466e9cf967c577077834de3fbb61a91ea24df21a268ac8713a2a7d017fc425774e3af773ccdf362acf6e9cb

test:
  secret_key_base: 41c3fa9b30b58013cc87c153c837216a33cde08e27bd1f084b23da78114fbede67f7a1cc7ad0be5625bbecf024e2d0c92504064182a4a5010a2bd2f8c6c9086f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
